/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "don:integration:<partition>:devo/<dev-org-id>:webhook/<webhook-id>",
 *         object: "ISS-12345"
 *     }
 */
export interface WebhooksFetchRequest {
    /** The ID of the webhook to fetch the object for. */
    id: string;
    /** The ID of the object to fetch for the webhook. */
    object: string;
}
