/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const DirectoriesGetRequest: core.serialization.Schema<
    serializers.DirectoriesGetRequest.Raw,
    DevRev.DirectoriesGetRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace DirectoriesGetRequest {
    interface Raw {
        id: string;
    }
}
