/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const DirectoriesCountRequest: core.serialization.Schema<
    serializers.DirectoriesCountRequest.Raw,
    DevRev.DirectoriesCountRequest
> = core.serialization.object({
    createdBy: core.serialization.property(
        "created_by",
        core.serialization.list(core.serialization.string()).optional()
    ),
    modifiedBy: core.serialization.property(
        "modified_by",
        core.serialization.list(core.serialization.string()).optional()
    ),
});

export declare namespace DirectoriesCountRequest {
    interface Raw {
        created_by?: string[] | null;
        modified_by?: string[] | null;
    }
}
