/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface RevUsersGetRequest {
    /** The ID of Rev user to be retrieved. */
    id: string;
}
