/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "ARTICLE-12345"
 *     }
 */
export interface ArticlesGetRequest {
    /** The ID of the required article. */
    id: string;
}
