/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const QuestionAnswersGetRequest: core.serialization.Schema<
    serializers.QuestionAnswersGetRequest.Raw,
    DevRev.QuestionAnswersGetRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace QuestionAnswersGetRequest {
    interface Raw {
        id: string;
    }
}
