/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const DevOrgAuthConnectionsGetRequest: core.serialization.Schema<
    serializers.DevOrgAuthConnectionsGetRequest.Raw,
    DevRev.DevOrgAuthConnectionsGetRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace DevOrgAuthConnectionsGetRequest {
    interface Raw {
        id: string;
    }
}
