/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const MeetingsDeleteRequest: core.serialization.Schema<
    serializers.MeetingsDeleteRequest.Raw,
    DevRev.MeetingsDeleteRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace MeetingsDeleteRequest {
    interface Raw {
        id: string;
    }
}
