/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         members: ["DEVU-12345"],
 *         scheduledDate: new Date("2023-01-01T12:00:00.000Z"),
 *         title: "title"
 *     }
 */
export interface EngagementsCreateRequest {
    /**
     * The IDs of the artifacts to associate with the engagement.
     *
     */
    artifacts?: string[];
    /** The description of the engagement. */
    description?: string;
    engagementType?: DevRev.EngagementsCreateRequestEngagementType;
    /** External Reference for the engagement. */
    externalRef?: string;
    /** External URL for the engagement. */
    externalUrl?: string;
    /** IDs of the users that were part of the engagement. */
    members: string[];
    /**
     * The parent object ID in which the engagement was created.
     * Currently, only accounts and opportunities are supported.
     *
     */
    parent?: string;
    /**
     * The parent object IDs to which the engagement is associated.
     * Currently, only accounts and opportunities are supported.
     *
     */
    parents?: string[];
    /** The date and time when the engagement was scheduled. */
    scheduledDate: Date;
    /** Tags associated with the engagement. */
    tags?: DevRev.SetTagWithValue[];
    /** The title of the engagement. */
    title: string;
}
