/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface EngagementsCountRequest {
    /** Filters for engagement of the provided types. */
    type?: DevRev.EngagementType[];
    /** Filters for meetings with the provided external_refs. */
    externalRef?: string[];
    /** Filters for engagement of the provided members. */
    members?: string[];
    /** Filters for engagements with the provided parent. */
    parent?: string[];
}
