/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         query: "query"
 *     }
 */
export interface GetReplyRequest {
    /** The query string. */
    query: string;
}
