/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface DirectoriesListRequest {
    /**
     * Filters for directories created by any of the provided users.
     *
     */
    createdBy?: string[];
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /**
     * The maximum number of directories to return. The default is '50'.
     *
     */
    limit?: number;
    mode?: DevRev.ListMode;
    /**
     * Filters for directories modified by any of the provided users.
     *
     */
    modifiedBy?: string[];
}
