/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         title: "title"
 *     }
 */
export interface DirectoriesCreateRequest {
    /** Description for the directory. */
    description?: string;
    /** Icon for the directory. */
    icon?: string;
    /** Parent directory of the directory. */
    parent?: string;
    /** Whether the directory is published. */
    published?: boolean;
    /** Tags associated with the directory. */
    tags?: DevRev.SetTagWithValue[];
    /** ID of the thumbnail artifact. */
    thumbnail?: string;
    /** Title of the directory. */
    title: string;
}
