/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DevOrgAuthConnectionsDeleteRequest {
    /** ID of the authentication connection to be deleted. */
    id: string;
}
