/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface ConversationsExportRequest {
    /**
     * Filters for conversations belonging to any of the provided parts.
     *
     */
    appliesToParts?: string[];
    /** Filters for custom fields. */
    customFields?: Record<string, unknown>;
    /**
     * The number of conversation items to return. The default is '50',
     * the maximum is '5000'.
     *
     */
    first?: number;
    /**
     * Filters for conversation that belong to the given groups.
     *
     */
    group?: string[];
    /**
     * Filters for conversations that are created by verified users.
     *
     */
    isCreatorVerified?: boolean;
    /** Filters for conversations that are spam. */
    isSpam?: boolean;
    /**
     * Filters for conversations where these users are participants.
     *
     */
    members?: string[];
    /** Filters for conversations owned by any of these users. */
    ownedBy?: string[];
    /**
     * Filters for conversations that are associated with any of the
     * provided Rev organizations.
     *
     */
    revOrg?: string[];
    /**
     * Filters for conversations that are associated with any of the
     * provided Rev organizations.
     *
     */
    revOrgs?: string[];
    slaSummary?: DevRev.SlaSummaryFilter;
    /**
     * Filters for conversations with any of the provided source channels.
     *
     */
    sourceChannel?: string[];
    /**
     * Filters for conversations with any of the provided source channels.
     *
     */
    sourceChannels?: string[];
    stage?: DevRev.StageFilter;
    /**
     * Filters for conversation with any of the provided subtypes.
     *
     */
    subtype?: string[];
    /** Filters for conversations with any of the provided tags. */
    tags?: string[];
    /**
     * Filters for conversations with any of the provided tags with value.
     *
     */
    tagsV2?: DevRev.TagWithValueFilter[];
}
