/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface UomsGetRequest {
    /** The Unit of Measurement (UOM)'s DON. */
    id: string;
}
