/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";
import { DateTimeFilter } from "../../../../types/DateTimeFilter";
import { ListMode } from "../../../../types/ListMode";

export const RevUsersListRequest: core.serialization.Schema<
    serializers.RevUsersListRequest.Raw,
    DevRev.RevUsersListRequest
> = core.serialization.object({
    createdBy: core.serialization.property(
        "created_by",
        core.serialization.list(core.serialization.string()).optional()
    ),
    createdDate: core.serialization.property("created_date", DateTimeFilter.optional()),
    cursor: core.serialization.string().optional(),
    customFields: core.serialization.property(
        "custom_fields",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional()
    ),
    email: core.serialization.list(core.serialization.string()).optional(),
    externalRef: core.serialization.property(
        "external_ref",
        core.serialization.list(core.serialization.string()).optional()
    ),
    isVerified: core.serialization.property("is_verified", core.serialization.boolean().optional()),
    limit: core.serialization.number().optional(),
    mode: ListMode.optional(),
    modifiedDate: core.serialization.property("modified_date", DateTimeFilter.optional()),
    phoneNumbers: core.serialization.property(
        "phone_numbers",
        core.serialization.list(core.serialization.string()).optional()
    ),
    revOrg: core.serialization.property("rev_org", core.serialization.list(core.serialization.string()).optional()),
    sortBy: core.serialization.property("sort_by", core.serialization.list(core.serialization.string()).optional()),
    tags: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace RevUsersListRequest {
    interface Raw {
        created_by?: string[] | null;
        created_date?: DateTimeFilter.Raw | null;
        cursor?: string | null;
        custom_fields?: Record<string, unknown> | null;
        email?: string[] | null;
        external_ref?: string[] | null;
        is_verified?: boolean | null;
        limit?: number | null;
        mode?: ListMode.Raw | null;
        modified_date?: DateTimeFilter.Raw | null;
        phone_numbers?: string[] | null;
        rev_org?: string[] | null;
        sort_by?: string[] | null;
        tags?: string[] | null;
    }
}
