/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const EventSourcesDeleteScheduledEventRequest: core.serialization.Schema<
    serializers.EventSourcesDeleteScheduledEventRequest.Raw,
    DevRev.EventSourcesDeleteScheduledEventRequest
> = core.serialization.object({
    eventKey: core.serialization.property("event_key", core.serialization.string()),
    id: core.serialization.string(),
});

export declare namespace EventSourcesDeleteScheduledEventRequest {
    interface Raw {
        event_key: string;
        id: string;
    }
}
