/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface DevUsersActivateRequest {
    /** IDs of the groups assigned to user during activation. */
    groups?: string[];
    /** The ID for the Dev User. */
    id: string;
}
