/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         devUser: "dev_user",
 *         issuer: "issuer"
 *     }
 */
export interface DevUsersIdentitiesUnlinkRequest {
    /**
     * The ID of the Dev user to unlink the external identity from.
     *
     */
    devUser: string;
    /** Issuer that needs to be unlinked from a Dev user. */
    issuer: string;
}
