/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         action: DevRev.MetricActionExecuteRequestAction.Complete,
 *         eventDate: new Date("2023-01-01T12:00:00.000Z"),
 *         metric: "metric",
 *         object: "object"
 *     }
 */
export interface MetricActionExecuteRequest {
    action: DevRev.MetricActionExecuteRequestAction;
    /** Timestamp of the event. */
    eventDate: Date;
    /**
     * The metric's ID for which the metric action is to be executed.
     *
     */
    metric: string;
    /**
     * The underlying object's ID on which the metric action is to be
     * executed.
     *
     */
    object: string;
}
