/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const IncidentsGetRequest: core.serialization.Schema<
    serializers.IncidentsGetRequest.Raw,
    DevRev.IncidentsGetRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace IncidentsGetRequest {
    interface Raw {
        id: string;
    }
}
