/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const AuthTokensDeleteRequest: core.serialization.Schema<
    serializers.AuthTokensDeleteRequest.Raw,
    DevRev.AuthTokensDeleteRequest
> = core.serialization.object({
    tokenId: core.serialization.property("token_id", core.serialization.string().optional()),
});

export declare namespace AuthTokensDeleteRequest {
    interface Raw {
        token_id?: string | null;
    }
}
