/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "ARTIFACT-12345"
 *     }
 */
export interface ArtifactsLocateRequest {
    /** The ID of the artifact to get the URL for. */
    id: string;
    /** The version of the artifact that needs to be fetched. */
    version?: string;
}
