/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const ArtifactsVersionsPrepareRequest: core.serialization.Schema<
    serializers.ArtifactsVersionsPrepareRequest.Raw,
    DevRev.ArtifactsVersionsPrepareRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace ArtifactsVersionsPrepareRequest {
    interface Raw {
        id: string;
    }
}
