/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const GroupMembersRemoveRequest: core.serialization.Schema<
    serializers.GroupMembersRemoveRequest.Raw,
    DevRev.GroupMembersRemoveRequest
> = core.serialization.object({
    group: core.serialization.string(),
    member: core.serialization.string(),
});

export declare namespace GroupMembersRemoveRequest {
    interface Raw {
        group: string;
        member: string;
    }
}
