/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "ACC-12345"
 *     }
 */
export interface AccountsDeleteRequest {
    /** The ID of account to delete. */
    id: string;
}
