/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface AccountsListRequest {
    /** Filters for accounts created by the specified user(s). */
    createdBy?: string[];
    createdDate?: DevRev.DateTimeFilter;
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /** Filters for custom fields. */
    customFields?: Record<string, unknown>;
    /** Array of display names of accounts to be filtered. */
    displayName?: string[];
    /** Domains for accounts to be filtered. */
    domains?: string[];
    /** Array of references of accounts to be filtered. */
    externalRefs?: string[];
    /**
     * The maximum number of accounts to return per page. The default is
     * '50'.
     *
     */
    limit?: number;
    mode?: DevRev.ListMode;
    modifiedDate?: DevRev.DateTimeFilter;
    /** Filters for accounts owned by the specified user(s). */
    ownedBy?: string[];
    /**
     * Fields to sort the accounts by and the direction to sort them in.
     *
     */
    sortBy?: string[];
    /** Filters for accounts on specified stages. */
    stage?: string[];
    /** List of tags to be filtered. */
    tags?: string[];
    /** Array of websites of accounts to be filtered. */
    websites?: string[];
}
