/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         displayName: "display_name"
 *     }
 */
export interface AccountsCreateRequest {
    /** The IDs of the artifacts to associate with the account. */
    artifacts?: string[];
    /** Application-defined custom fields. */
    customFields?: Record<string, unknown>;
    customSchemaSpec?: DevRev.CustomSchemaSpec;
    /** Description of the account. */
    description?: string;
    /** Name of the account. */
    displayName: string;
    /** List of company's domain names. Example - ['devrev.ai']. */
    domains?: string[];
    /**
     * External refs are unique identifiers from your customer system of
     * records, stored as a list.
     *
     */
    externalRefs?: string[];
    /** List of Dev users owning this account. */
    ownedBy?: string[];
    /** Schema fragment IDs associated with this account SOR. */
    schemaFragmentIds?: string[];
    /** Tags associated with the account. */
    tags?: DevRev.SetTagWithValue[];
    /** The tier of the account. */
    tier?: string;
    /**
     * List of company websites. Example - ['www.devrev.ai',
     * 'www.marketplace.devrev.ai'].
     *
     */
    websites?: string[];
}
