/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface IncidentsUpdateRequest {
    /** Timestamp when the incident was acknowledged. */
    acknowledgedDate?: Date;
    appliesToParts?: DevRev.UpdateIncidentAppliesToParts;
    artifacts?: DevRev.UpdateIncidentArtifacts;
    /** Body of the incident. */
    body?: string;
    /** Application-defined custom fields. */
    customFields?: Record<string, unknown>;
    customSchemaSpec?: DevRev.CustomSchemaSpec;
    /** The ID of the incident to be updated. */
    id: string;
    /** Time when the incident was identified/reported. */
    identifiedDate?: Date;
    impact?: DevRev.UpdateImpactedCustomerDetails;
    impactedCustomers?: DevRev.UpdateIncidentImpactedCustomers;
    /** Timestamp when the incident was mitigated. */
    mitigatedDate?: Date;
    ownedBy?: DevRev.UpdateIncidentOwnedBy;
    pia?: DevRev.UpdateIncidentPia;
    playbooks?: DevRev.UpdateIncidentPlaybooks;
    relatedDocs?: DevRev.UpdateIncidentRelatedDocs;
    /** The entity that first reported the incident. */
    reportedBy?: number;
    /** Severity of the incident. */
    severity?: number;
    /**
     * Source of where the incident was created. Only sys users and
     * service accounts are supposed to set this field.
     *
     */
    source?: number;
    stage?: DevRev.UpdateStage;
    stakeholders?: DevRev.UpdateIncidentStakeholders;
    tags?: DevRev.UpdateIncidentTags;
    /** Timestamp when the incident is expected to be resolved. */
    targetCloseDate?: Date;
    /** Title of the incident. */
    title?: string;
}
