/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         eventKey: "event_key",
 *         id: "id"
 *     }
 */
export interface EventSourcesDeleteScheduledEventRequest {
    /** The event key for the event which we want to delete. */
    eventKey: string;
    /** The event source's ID. */
    id: string;
}
