/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface Account extends DevRev.OrgBase {
    /** The artifacts attached to the Account. */
    artifacts?: DevRev.ArtifactSummary[];
    /** Custom fields. */
    customFields?: Record<string, unknown>;
    /** Custom schema fragments. */
    customSchemaFragments?: string[];
    /** Description of the corresponding Account. */
    description?: string;
    /** Company's domain names. Example - 'devrev.ai'. */
    domains?: string[];
    /**
     * External refs are unique identifiers from your customer system of
     * records, stored as a list.
     */
    externalRefs: string[];
    /** List of Dev user IDs owning this Account. */
    ownedBy: DevRev.UserSummary[];
    /** Stock schema fragment. */
    stockSchemaFragment?: string;
    /** Subtype corresponding to the custom type fragment. */
    subtype?: string;
    /** Tags associated with an object. */
    tags?: DevRev.TagWithValue[];
    /** The Tier of the corresponding Account. */
    tier?: string;
    /**
     * Company's website links. Filling in this property will also fill in
     * domain. Example - 'www.devrev.ai'.
     */
    websites?: string[];
}
