/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface ArticlesUpdateRequestTags {
    /** Sets the provided tags on the article. */
    set?: DevRev.SetTagWithValue[];
}
