/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * The response to getting an artifact's information.
 */
export interface ArtifactsGetResponse {
    artifact: DevRev.Artifact;
    version: DevRev.ArtifactVersion;
}
