/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface ArtifactsVersionsPrepareResponseFormData {
    /** Key of the form field. */
    key: string;
    /** Value corresponding to the key. */
    value: string;
}
