/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of the article.
 */
export type ArticleType = "article" | "content_block";

export const ArticleType = {
    Article: "article",
    ContentBlock: "content_block",
} as const;
