/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The Dev organization attributes extracted from the auth token.
 */
export interface AuthTokensOrgAttributes {
    /** The display ID of the Dev organization. */
    displayId: string;
    /** The ID of the the Dev organization. */
    id: string;
    /** The slug of the Dev organization. */
    slug?: string;
}
