/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of the subject token.
 */
export type AuthTokenSubjectTokenType =
    | "urn:devrev:params:oauth:token-type:jwt:auth0"
    | "urn:devrev:params:oauth:token-type:jwt:dev"
    | "urn:devrev:params:oauth:token-type:rat"
    | "urn:devrev:params:oauth:token-type:rev"
    | "urn:devrev:params:oauth:token-type:revinfo"
    | "urn:devrev:params:oauth:token-type:session"
    | "urn:devrev:params:oauth:token-type:sysu"
    | "urn:devrev:params:oauth:token-type:userinfo"
    | "urn:ietf:params:oauth:token-type:jwt";

export const AuthTokenSubjectTokenType = {
    UrnDevrevParamsOauthTokenTypeJwtAuth0: "urn:devrev:params:oauth:token-type:jwt:auth0",
    UrnDevrevParamsOauthTokenTypeJwtDev: "urn:devrev:params:oauth:token-type:jwt:dev",
    UrnDevrevParamsOauthTokenTypeRat: "urn:devrev:params:oauth:token-type:rat",
    UrnDevrevParamsOauthTokenTypeRev: "urn:devrev:params:oauth:token-type:rev",
    UrnDevrevParamsOauthTokenTypeRevinfo: "urn:devrev:params:oauth:token-type:revinfo",
    UrnDevrevParamsOauthTokenTypeSession: "urn:devrev:params:oauth:token-type:session",
    UrnDevrevParamsOauthTokenTypeSysu: "urn:devrev:params:oauth:token-type:sysu",
    UrnDevrevParamsOauthTokenTypeUserinfo: "urn:devrev:params:oauth:token-type:userinfo",
    UrnIetfParamsOauthTokenTypeJwt: "urn:ietf:params:oauth:token-type:jwt",
} as const;
