/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Carries Rev org info.
 */
export interface AuthTokensOrgTraits {
    /** Application-defined custom fields of the Rev org. */
    customFields?: Record<string, unknown>;
    /** The description of the Rev org. */
    description?: string;
    /** The display name of the Rev org. */
    displayName?: string;
    /** The domain of the Rev org. */
    domain?: string;
    /** Phone numbers of the Rev org. */
    phoneNumbers?: string[];
    /** The tier of the Rev org. */
    tier?: string;
}
