/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Object encapsulating the configuration parameters for a Google Apps
 * authentication connection.
 */
export interface AuthConnectionOptionsGoogleApps {
    /** Client ID for the Google Apps authentication connection. */
    clientId: string;
    /** Tenant domain URL of the Google Apps authentication connection. */
    tenantDomain: string;
}
