/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Properties of client's page to be used in track API.
 */
export interface ClientContextPage {
    /** Page domain, example: devrev.ai */
    domain?: string;
    /** Page path, example: /pricing */
    path?: string;
    /** Page referrer, example: https://devrev.ai */
    referrer?: string;
    /** Page title, example: Pricing */
    title?: string;
    /** Page URL, example: https://devrev.ai/pricing */
    url?: string;
}
