/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface CustomStageSummary extends DevRev.AtomBaseSummary {
    /** The human readable name of the state. */
    name?: string;
}
