/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface CustomTypeFragment extends DevRev.CustomSchemaFragmentBase {
    stageDiagram?: DevRev.StageDiagramSummary;
    /** The stock field overrides. */
    stockFieldOverrides?: DevRev.StockFieldOverride[];
    /** The string used to populate the subtype in the leaf type. */
    subtype?: string;
    /**
     * Display name of the subtype. Modifications to this field are done
     * in-place and don't result in creation of a new fragment in chain.
     */
    subtypeDisplayName?: string;
}
