/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates whether this evaluation can change in the future.
 */
export type Definedness = "immutable" | "mutable" | "undefined";

export const Definedness = {
    Immutable: "immutable",
    Mutable: "mutable",
    Undefined: "undefined",
} as const;
