/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface DevUser extends DevRev.UserBase {
    /** Custom fields. */
    customFields?: Record<string, unknown>;
    /** Custom schema fragments. */
    customSchemaFragments?: string[];
    /** Start date of the user's employment. */
    experienceStartDate?: Date;
    /** IDs of the Dev User outside the DevRev SOR. */
    externalIdentities?: DevRev.ExternalIdentity[];
    /** Job history of the user. */
    jobHistory?: DevRev.JobHistoryItem[];
    /** Array of skills of the user. */
    skills?: DevRev.UserSkill[];
    /** Stock schema fragment. */
    stockSchemaFragment?: string;
    /** Subtype corresponding to the custom type fragment. */
    subtype?: string;
}
