/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * Response for the request to unlink an external identity from a Dev
 * user.
 */
export interface DevUsersIdentitiesUnlinkResponse {
    devUser: DevRev.DevUser;
}
