/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * Update directory response.
 */
export interface DirectoriesUpdateResponse {
    directory: DevRev.Directory;
}
