/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface DirectoriesUpdateRequestTags {
    /** Sets the provided tags on the directory. */
    set?: DevRev.SetTagWithValue[];
}
