/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EngagementsUpdateRequestMembers {
    /**
     * Sets the members to the provided user IDs. If specified, this must
     * not be empty.
     */
    set?: string[];
}
