/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Status of the event source. Note that paused/blocked event sources
 * return NotFound error on triggering.
 */
export type EventSourceStatus = "active" | "blocked" | "paused";

export const EventSourceStatus = {
    Active: "active",
    Blocked: "blocked",
    Paused: "paused",
} as const;
