/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface EventSourcesScheduleEventResponse {
    /**
     * The event key for this event. Auto-generated if the caller doesn't
     * specify the event key. This may be empty if the event was published
     * immediately.
     */
    eventKey?: string;
}
