/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * External identity of a user.
 */
export interface ExternalIdentity {
    /** Display name of the user in the external source. */
    displayName?: string;
    /** Unique ID of the user in the external source. */
    id?: string;
    /** Whether the external identity is verified or not. */
    isVerified?: boolean;
    /** Issuer of the external identity of the user. */
    issuer?: string;
}
