/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface GroupSummary extends DevRev.AtomBaseSummary {
    memberType?: DevRev.GroupMemberType;
    /** Name of the group. */
    name?: string;
}
