/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface IssueSummary extends DevRev.WorkBaseSummary {
    priority?: DevRev.IssuePriority;
    sprint?: DevRev.VistaGroupItemSummary;
}
