/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * Defines a job history line item.
 */
export interface JobHistoryItem {
    employmentStatus?: DevRev.EnumValue;
    /** The end date of the job, or not specified if current. */
    endDate?: Date;
    /** Is this the current active job for the user. */
    isCurrent?: boolean;
    /** The job location for the user. */
    location?: string;
    /** The start date of the job. */
    startDate?: Date;
    /** The job title for the user. */
    title?: string;
}
