/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * The response to creating a new link.
 */
export interface LinksCreateResponse {
    link: DevRev.Link;
}
