/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Type of link used to define the relationship.
 */
export type LinkType =
    | "custom_link"
    | "developed_with"
    | "imports"
    | "is_analyzed_by"
    | "is_converted_to"
    | "is_dependent_on"
    | "is_duplicate_of"
    | "is_follow_up_of"
    | "is_merged_into"
    | "is_parent_of"
    | "is_part_of"
    | "is_related_to"
    | "serves";

export const LinkType = {
    CustomLink: "custom_link",
    DevelopedWith: "developed_with",
    Imports: "imports",
    IsAnalyzedBy: "is_analyzed_by",
    IsConvertedTo: "is_converted_to",
    IsDependentOn: "is_dependent_on",
    IsDuplicateOf: "is_duplicate_of",
    IsFollowUpOf: "is_follow_up_of",
    IsMergedInto: "is_merged_into",
    IsParentOf: "is_parent_of",
    IsPartOf: "is_part_of",
    IsRelatedTo: "is_related_to",
    Serves: "serves",
} as const;
