/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The channel of meeting.
 */
export type MeetingChannel = "google_meet" | "offline" | "other" | "teams" | "zoom";

export const MeetingChannel = {
    GoogleMeet: "google_meet",
    Offline: "offline",
    Other: "other",
    Teams: "teams",
    Zoom: "zoom",
} as const;
