/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of the metric. 'time' metrics track the time spent in some
 * state, supporting operations like 'start', 'stop', 'pause', 'resume'.
 * 'value' metrics track a value, supporting operations like 'set',
 * 'increment', 'decrement'.
 */
export type MetricDefinitionMetricType = "time" | "value";

export const MetricDefinitionMetricType = {
    Time: "time",
    Value: "value",
} as const;
