/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface MetricsData {
    /**
     * Account ID or external_ref of the account for which metric is being
     * published. Account ID is DevRev DON ID. For example,
     * don:identity:dvrv-us-1:devo/0:account/156. External_ref is the
     * identification of DevRev customer's customers. Devrev will
     * internally resolve external_ref to Account ID and use it for
     * further processing. For example, external_ref=customer_1 may
     * resolve to don:identity:dvrv-us-1:devo/0:account/155.
     */
    accountRef: string;
    /**
     * One or more data points collected for a given metric such as object
     * usage, object state etc.
     */
    dataPoints: DevRev.MetricDataPoint[];
    /**
     * Name of the metric which is being measured. For example,
     * num_api_calls, num_active_users, etc.
     */
    name: string;
    /**
     * Rev Org ID or external_ref for which metric is being published.Rev
     * Org ID is DevRev DON ID. For example,
     * don:identity:dvrv-us-1:devo/0:revo/156. External_ref is the
     * identification of DevRev customer's customers and maintained by
     * DevRev's customers. Devrev will internally resolve external_ref to
     * Rev Org ID and use it for further processing. For example,
     * external_ref=org_customer_1 may resolve to
     * don:identity:dvrv-us-1:devo/0:revo/155.
     */
    orgRef?: string;
    /** Rev User ID or user ref for which metric is being published. */
    userRef?: string;
}
