/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Money.
 */
export interface Money {
    /** Amount of the money. */
    amount?: string;
    /** Currency of the money. */
    currency?: string;
}
