/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface OrgScheduleSummary extends DevRev.AtomBaseSummary {
    /** Human-readable name. */
    name?: string;
    status: DevRev.OrgScheduleStatus;
    /**
     * Timezone in which this is defined. Only organization schedules in
     * the same timezone can be directly combined.
     */
    timezone?: string;
    /**
     * Derived field indicating when a valid organization schedule will
     * become invalid. If omitted, the schedule is already invalid. A
     * schedule is valid if it has a weekly schedule for all named periods
     * for all its schedule fragments, and if it has a schedule fragment
     * for the time period in question.
     */
    validUntil?: Date;
}
