/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface QuestionAnswerSummary extends DevRev.AtomBaseSummary {
    /** The Question. */
    question?: string;
}
