/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * List question-answers response.
 */
export interface QuestionAnswersListResponse {
    /**
     * The cursor used to iterate subsequent results in accordance to the
     * sort order. If not set, then no later elements exist.
     */
    nextCursor?: string;
    /**
     * The cursor used to iterate preceding results in accordance to the
     * sort order. If not set, then no prior elements exist.
     */
    prevCursor?: string;
    /** The question-answers entries matching the request. */
    questionAnswers: DevRev.QuestionAnswer[];
    /** Total number of question-answer items for the request. */
    total: number;
}
