/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * Response object for creating a new Rev user for Rev organization.
 */
export interface RevUsersCreateResponse {
    revUser: DevRev.RevUser;
}
