/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The response to deleting a Rev user of a Rev organization.
 */
export type RevUsersDeleteResponse = Record<string, unknown>;
