/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface SchemaFieldDescriptorBase {
    /** Description of the field. */
    description?: string;
    /** Whether this field is filterable, groupable and sortable. */
    isFilterable?: boolean;
    /** Whether this field is immutable or not. */
    isImmutable?: boolean;
    /**
     * Whether this field can hold Personally Identifiable Information
     * (PII).
     */
    isPii?: boolean;
    /** Whether this field is required or not. */
    isRequired?: boolean;
    mfz?: DevRev.SchemaFieldMfzMetadata;
    /** Name of the field. */
    name: string;
    oasis?: DevRev.SchemaFieldOasisMetadata;
    /** Type this field is from. */
    origin?: string;
    ui?: DevRev.SchemaFieldUiMetadata;
}
