/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface SchemaDoubleFieldDescriptor extends DevRev.SchemaFieldDescriptorBase {
    /** Default value. */
    defaultValue?: number;
}
