/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * List view UI hint overrides.
 */
export interface SchemaFieldListViewUiMetadata {
    /** Whether the field is hidden in the UI list view. */
    isHidden?: boolean;
}
