/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Search sort by parameters.
 */
export type SearchSortByParam = "created_date" | "modified_date" | "relevance";

export const SearchSortByParam = {
    CreatedDate: "created_date",
    ModifiedDate: "modified_date",
    Relevance: "relevance",
} as const;
