/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Describes the compensation to be provided in case of SLA breach. It is
 * not 'self-executing', it is the responsibility of the organization
 * providing the SLA to actually transfer the promised credit, resource or
 * other payment.
 */
export type SlaCompensation = Record<string, unknown>;
