/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface SnapIn extends DevRev.AtomBase {
    /** Values of the inputs. */
    inputsValues?: Record<string, unknown>;
}
