/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Logical grouping of snap widgets. Useful for filtering.
 */
export type SnapWidgetNamespace =
    | "ai_assistant_message"
    | "comment_suggestion_replies"
    | "email_preview"
    | "link_preview"
    | "plug_nudge";

export const SnapWidgetNamespace = {
    AiAssistantMessage: "ai_assistant_message",
    CommentSuggestionReplies: "comment_suggestion_replies",
    EmailPreview: "email_preview",
    LinkPreview: "link_preview",
    PlugNudge: "plug_nudge",
} as const;
