/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the snap widget.
 */
export type SnapWidgetStatus = "draft" | "published";

export const SnapWidgetStatus = {
    Draft: "draft",
    Published: "published",
} as const;
