/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface StockSchemaFragment extends DevRev.AtomBase {
    /** Description of the schema. */
    description?: string;
    /** List of all fields in this schema. */
    fields: DevRev.SchemaFieldDescriptor[];
    /** Leaf type this fragment applies to. */
    leafType?: string;
    newFragmentRef?: DevRev.AtomSummary;
    oldFragmentRef?: DevRev.AtomSummary;
    /** Title of the schema. */
    title?: string;
}
