/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * A stock field override.
 */
export interface StockFieldOverride {
    /** Whether the field is required. */
    isRequired?: boolean;
    /** Name of the stock field to be overridden. */
    name?: string;
    /** Overridden allowed values for a unified enum. */
    uenumValues?: DevRev.SchemaFieldUenumValue[];
    ui?: DevRev.SchemaFieldUiMetadata;
}
