/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface SurveyResponse extends DevRev.AtomBase {
    /** The unique ID associated with the dispatched survey. */
    dispatchId?: string;
    /** Source channels on which the survey is sent. */
    dispatchedChannels?: DevRev.EnumValue[];
    /** The ID of the object for which survey is taken. */
    object?: string;
    recipient?: DevRev.UserSummary;
    /** Response for the survey. */
    response?: Record<string, unknown>;
    responseChannel?: DevRev.EnumValue;
    stage?: DevRev.EnumValue;
    /** The ID of the survey for which response is taken. */
    survey?: string;
}
