/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * Object for holding run-specific data.
 */
export interface SyncRunSummary {
    mode?: DevRev.SyncRunMode;
    progress?: DevRev.SyncProgressSummary;
}
