/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface SyncMetadataFilterSyncOutFilter {
    /** Filters for works with selected sync statuses. */
    status?: DevRev.SyncMetadataFilterSyncOutFilterStatus[];
    syncDate?: DevRev.DateFilter;
    /** Filters for works modified with selected sync units. */
    syncUnit?: string[];
}
