/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Severity of the ticket.
 */
export type TicketSeverity = "blocker" | "high" | "low" | "medium";

export const TicketSeverity = {
    Blocker: "blocker",
    High: "high",
    Low: "low",
    Medium: "medium",
} as const;
