/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Display panels for the Timeline entry.
 */
export type TimelineEntryPanel = "alerts" | "broadcasts" | "customer_chat" | "discussions" | "events";

export const TimelineEntryPanel = {
    Alerts: "alerts",
    Broadcasts: "broadcasts",
    CustomerChat: "customer_chat",
    Discussions: "discussions",
    Events: "events",
} as const;
