/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Snap Kit Body of the comment.
 */
export interface TimelineSnapKitBody {
    /** The JSON body of the SnapKit. */
    body?: Record<string, unknown>;
    /**
     * The name of an action defined in the SnapIn. The combination of
     * snap_in_id and snap_in_action_name uniquely identifies the
     * interaction object which is to be called when actions on a snapkit
     * element is taken.
     */
    snapInActionName?: string;
    /** ID of the snap-in which created the SnapKit. */
    snapInId?: string;
}
