/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

/**
 * Unit encapsulates the name of the unit and the type of the unit. For
 * example, '#Number of API calls' where name is 'number_of_api_calls' and
 * type is 'number'.
 */
export interface Unit {
    type: DevRev.UnitType;
    /**
     * This represents human readable unit name of the UOM For example,
     * number of API calls.
     */
    name: string;
}
