/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export interface UpdateImpactedCustomerDetails {
    /** Count of customers impacted. */
    count?: number;
    customerIds?: DevRev.UpdateImpactedCustomerDetailsCustomerIds;
}
