/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Update object for TagWithValue.
 */
export interface UpdateTagWithValue {
    /** ID of the referenced tag */
    tagId?: string;
    /** Value associated with the tag for the object. */
    value?: string;
}
