/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface UpdateIncidentPlaybooks {
    /**
     * Sets the the article ids of the playbook(s) associated with the
     * incident.
     */
    set?: string[];
}
