/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorksUpdateRequestArtifacts {
    /** Adds the provided artifacts (if not already present) to the field. */
    add?: string[];
    /** Removes the provided artifacts (if they exist) from the field. */
    remove?: string[];
    /** Sets the field to the provided artifacts. */
    set?: string[];
}
