/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../index";

export type WorksUpdateRequest =
    | DevRev.WorksUpdateRequest.Issue
    | DevRev.WorksUpdateRequest.None
    | DevRev.WorksUpdateRequest.Opportunity
    | DevRev.WorksUpdateRequest.Task
    | DevRev.WorksUpdateRequest.Ticket;

export declare namespace WorksUpdateRequest {
    interface Issue extends DevRev.WorksUpdateRequestIssue, _Base {
        type: "issue";
    }

    interface None extends _Base {
        type: "none";
        value: DevRev.Empty;
    }

    interface Opportunity extends DevRev.WorksUpdateRequestOpportunity, _Base {
        type: "opportunity";
    }

    interface Task extends DevRev.WorksUpdateRequestTask, _Base {
        type: "task";
    }

    interface Ticket extends DevRev.WorksUpdateRequestTicket, _Base {
        type: "ticket";
    }

    interface _Base {
        /** Updates the part that the work item applies to. */
        appliesToPart?: string;
        artifacts?: DevRev.WorksUpdateRequestArtifacts;
        /** Updated body of the work object, or unchanged if not provided. */
        body?: string;
        /** Custom fields. */
        customFields?: Record<string, unknown>;
        /** The custom schema fragments to use. */
        customSchemaFragments?: string[];
        customSchemaSpec?: DevRev.CustomSchemaSpec;
        /** The work's ID. */
        id: string;
        ownedBy?: DevRev.WorksUpdateRequestOwnedBy;
        reportedBy?: DevRev.WorksUpdateRequestReportedBy;
        stage?: DevRev.StageUpdate;
        /**
         * The type of stage validations options when updating the stage of an
         * object.
         */
        stageValidationOptions?: DevRev.StageValidationOptionForUpdate[];
        stagedInfo?: DevRev.WorksUpdateRequestStagedInfoUpdate;
        tags?: DevRev.WorksUpdateRequestTags;
        /** Updates the timestamp for when the work is expected to be complete. */
        targetCloseDate?: Date;
        /** Updated title of the work object, or unchanged if not provided. */
        title?: string;
    }
}
