/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorksUpdateRequestOwnedBy {
    /**
     * Sets the owner IDs to the provided user IDs. This must not be
     * empty.
     */
    set?: string[];
}
