/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface AuthTokensSelfDeleteRequest {
    requestedTokenType?: DevRev.AuthTokenRequestedTokenType;
}
