/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface AuthTokensListRequest {
    /**
     * An identifier that represents the application, which requested the
     * token. Only relevant for application access tokens.
     *
     */
    clientId?: string;
    requestedTokenType?: DevRev.AuthTokenRequestedTokenType;
    /**
     * The subject associated with the token. In the absence of this
     * parameter, the ID of the authenticated entity is treated as the
     * subject.
     *
     */
    subject?: string;
}
