/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const PreferencesGetRequest: core.serialization.Schema<
    serializers.PreferencesGetRequest.Raw,
    DevRev.PreferencesGetRequest
> = core.serialization.object({
    object: core.serialization.string(),
});

export declare namespace PreferencesGetRequest {
    interface Raw {
        object: string;
    }
}
