/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         namespace: DevRev.SearchHybridNamespace.Article,
 *         query: "query"
 *     }
 */
export interface SearchHybridRequest {
    /**
     * The maximum number of items to return in a page. The default is
     * '10'.
     *
     */
    limit?: number;
    namespace: DevRev.SearchHybridNamespace;
    /** The query string. */
    query: string;
    /**
     * The weightage for semantic search. Values between 0 and 1 are
     * accepted.
     *
     */
    semanticWeight?: number;
}
