/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface MeetingsListRequest {
    /** Filters for meeting on specified channels. */
    channel?: DevRev.MeetingChannel[];
    /** Filters for meetings created by the specified user(s). */
    createdBy?: string[];
    createdDate?: DevRev.DateFilter;
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /** Filters for meeting on custom fields. */
    customFields?: Record<string, unknown>;
    /** Filters for meetings with the provided external_ref(s). */
    externalRef?: string[];
    /** The maximum number of meetings to return. */
    limit?: number;
    /** Filters for links associated with the meeting. */
    links?: DevRev.MeetingsFilterLinkSummaryFilter[];
    /** Filter for meeting on specified Member Ids. */
    members?: string[];
    mode?: DevRev.ListMode;
    modifiedDate?: DevRev.DateFilter;
    /** Filter for meeting on specified organizers. */
    organizer?: string[];
    /** Filters for meetings with the provided parent. */
    parent?: string[];
    /**
     * Fields to sort the meetings by and the direction to sort them.
     *
     */
    sortBy?: string[];
    /** Filters for meeting on specified state or outcomes. */
    state?: DevRev.MeetingState[];
    /** Filters for meeting by tags. */
    tags?: string[];
}
