/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface MeetingsUpdateRequest {
    channel?: DevRev.MeetingChannel;
    /** Application-defined custom fields. */
    customFields?: Record<string, unknown>;
    /** The description of the meeting. */
    description?: string;
    /** Updates the date and time when the meeting ended. */
    endedDate?: Date;
    /** External Reference for the meeting. */
    externalRef?: string;
    /** External URL for the meeting. */
    externalUrl?: string;
    /** The meetings ID. */
    id: string;
    members?: DevRev.MeetingsUpdateRequestMembers;
    /** The ID of the user who organized the meeting. */
    organizer?: string;
    /** The recording URL of the meeting. */
    recordingUrl?: string;
    /**
     * Updates the date and time when the meeting was scheduled.
     *
     */
    scheduledDate?: Date;
    state?: DevRev.MeetingState;
    tags?: DevRev.MeetingsUpdateRequestTags;
    /** The title of the meeting. */
    title?: string;
}
