/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         object: "ACC-12345",
 *         survey: "survey"
 *     }
 */
export interface SurveysSubmitRequest {
    /** The unique ID associated with the dispatched survey. */
    dispatchId?: string;
    /**
     * The ordinals of the source channels on which the survey is sent.
     *
     */
    dispatchedChannels?: number[];
    /**
     * The ID of the object this survey is on (e.g. ticket, conversation,
     * etc).
     *
     */
    object: string;
    /**
     * The unique ID associated with the recipient of the survey.
     *
     */
    recipient?: string;
    /** Survey response submitted for the object. */
    response?: Record<string, unknown>;
    /**
     * The response score for the survey. Only applicable for CSAT and
     * NPS.
     *
     */
    responseScore?: number;
    /**
     * The source channel from which survey response is submitted.
     *
     */
    sourceChannel?: string;
    /** The stage ordinal of the survey response object. */
    stage?: number;
    /** The ID of the survey to submit the response to. */
    survey: string;
}
