/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface SurveysResponsesListRequest {
    /**
     * Filters for survey responses created by any of these users.
     *
     */
    createdBy?: string[];
    createdDate?: DevRev.DateFilter;
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /**
     * The maximum number of survey responses to return. If not set, then
     * the default is '50'.
     *
     */
    limit?: number;
    mode?: DevRev.ListMode;
    modifiedDate?: DevRev.DateFilter;
    /** Filters for survey responses created for the objects. */
    objects?: string[];
    /**
     * Filters for survey responses dispatched to any of these users.
     *
     */
    recipient?: string[];
    /**
     * Fields to sort the survey responses by and the direction to sort
     * them.
     *
     */
    sortBy?: string[];
    /** Filters for survey response stages. */
    stages?: number[];
    /**
     * Filters for survey responses for the provided survey IDs.
     *
     */
    surveys?: string[];
}
