/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "name",
 *         ordinal: 1
 *     }
 */
export interface CustomStatesCreateRequest {
    /** Whether this is a final state. */
    isFinal?: boolean;
    /** The name of the custom state. */
    name: string;
    /**
     * Ordinal of the custom state used to identify system states.
     *
     */
    ordinal: number;
}
