/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CustomLinkTypeUpdateRequest {
    /** The updated name of the link in the backward direction. */
    backwardName?: string;
    /** Whether the link type is deprecated. */
    deprecated?: boolean;
    /** The updated name of the link in the forward direction. */
    forwardName?: string;
    /** The ID of the custom link type to update. */
    id: string;
    /** The updated name of the custom link type. */
    name?: string;
    sourceTypes?: DevRev.UpdateLinkTargetDescriptorList;
    targetTypes?: DevRev.UpdateLinkTargetDescriptorList;
    /** The updated tooltip of the custom link type. */
    tooltip?: string;
}
