/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CustomObjectsUpdateRequest {
    /** Custom fields of the custom object. */
    customFields?: Record<string, unknown>;
    customSchemaSpec?: DevRev.CustomSchemaSpec;
    /** The ID of the custom object to update. */
    id: string;
    /** Updates the stage of the custom object. */
    stage?: string;
    /**
     * The type of stage validations options when updating the stage of a
     * custom object.
     *
     */
    stageValidationOptions?: DevRev.StageValidationOptionForUpdate[];
    /** Updates the title of the custom object. */
    title?: string;
}
