/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         id: "id"
 *     }
 */
export interface CustomStatesGetRequest {
    /** The ID of the custom state to get. */
    id: string;
}
