/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         leafType: "leaf_type"
 *     }
 */
export interface CustomObjectsListRequest {
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /** List of filters to apply. */
    filter?: unknown[];
    /** Leaf type to filter. */
    leafType: string;
    /** The maximum number of items. */
    limit?: number;
    mode?: DevRev.ListMode;
    /**
     * The list of fields to sort the items by and how to sort them.
     *
     */
    sortBy?: string[];
}
