/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {}
 */
export interface CustomLinkTypeListRequest {
    /**
     * The cursor to resume iteration from. If not provided, then
     * iteration starts from the beginning.
     *
     */
    cursor?: string;
    /** Whether only deprecated link types should be filtered. */
    deprecated?: boolean;
    /** The maximum number of items. */
    limit?: number;
    mode?: DevRev.ListMode;
    /** The list of link type names. */
    name?: string[];
    /**
     * The list of fields to sort the items by and how to sort them.
     *
     */
    sortBy?: string[];
    sourceTypes?: DevRev.LinkDescriptorFilter;
    targetTypes?: DevRev.LinkDescriptorFilter;
}
