/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const DevRevEnvironment = {
    Default: "https://api.devrev.ai",
} as const;

export type DevRevEnvironment = typeof DevRevEnvironment.Default;
