/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const DevUsersIdentitiesUnlinkRequest: core.serialization.Schema<
    serializers.DevUsersIdentitiesUnlinkRequest.Raw,
    DevRev.DevUsersIdentitiesUnlinkRequest
> = core.serialization.object({
    devUser: core.serialization.property("dev_user", core.serialization.string()),
    issuer: core.serialization.string(),
});

export declare namespace DevUsersIdentitiesUnlinkRequest {
    interface Raw {
        dev_user: string;
        issuer: string;
    }
}
