/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DevRev from "../../../../index";

/**
 * @example
 *     {
 *         from: new Date("2023-01-01T12:00:00.000Z"),
 *         intervals: [{
 *                 from: new Date("2023-01-01T12:00:00.000Z"),
 *                 name: "name"
 *             }],
 *         name: "name",
 *         to: new Date("2023-01-01T12:00:00.000Z")
 *     }
 */
export interface OrgScheduleFragmentsCreateRequest {
    /**
     * Date (inclusive) on which the organization schedule fragment
     * begins.
     *
     */
    from: Date;
    /** The intervals that comprise the schedule fragment. */
    intervals: DevRev.CreateOrgScheduleInterval[];
    /** Name of the organization schedule fragment. */
    name: string;
    /**
     * CLDR region code of the countries/regions it is meant to be valid
     * for. Does not drive logic, serves only for easier filtering and
     * organization.
     *
     */
    regionCodes?: string[];
    /**
     * Date (exclusive) on which the organization schedule fragment's
     * validity ends.
     *
     */
    to: Date;
}
