/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Account } from "./Account";

export const AccountsGetResponse: core.serialization.ObjectSchema<
    serializers.AccountsGetResponse.Raw,
    DevRev.AccountsGetResponse
> = core.serialization.object({
    account: Account,
});

export declare namespace AccountsGetResponse {
    interface Raw {
        account: Account.Raw;
    }
}
