/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Article } from "./Article";

export const ArticlesUpdateResponse: core.serialization.ObjectSchema<
    serializers.ArticlesUpdateResponse.Raw,
    DevRev.ArticlesUpdateResponse
> = core.serialization.object({
    article: Article,
});

export declare namespace ArticlesUpdateResponse {
    interface Raw {
        article: Article.Raw;
    }
}
