/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { ArticleSummary } from "./ArticleSummary";
import { SearchSummaryBase } from "./SearchSummaryBase";

export const ArticleSearchSummary: core.serialization.ObjectSchema<
    serializers.ArticleSearchSummary.Raw,
    DevRev.ArticleSearchSummary
> = core.serialization
    .object({
        article: ArticleSummary,
    })
    .extend(SearchSummaryBase);

export declare namespace ArticleSearchSummary {
    interface Raw extends SearchSummaryBase.Raw {
        article: ArticleSummary.Raw;
    }
}
