/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Artifact } from "./Artifact";

export const ArtifactsListResponse: core.serialization.ObjectSchema<
    serializers.ArtifactsListResponse.Raw,
    DevRev.ArtifactsListResponse
> = core.serialization.object({
    artifacts: core.serialization.list(Artifact),
});

export declare namespace ArtifactsListResponse {
    interface Raw {
        artifacts: Artifact.Raw[];
    }
}
