/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const AuthTokensOrgAttributes: core.serialization.ObjectSchema<
    serializers.AuthTokensOrgAttributes.Raw,
    DevRev.AuthTokensOrgAttributes
> = core.serialization.object({
    displayId: core.serialization.property("display_id", core.serialization.string()),
    id: core.serialization.string(),
    slug: core.serialization.string().optional(),
});

export declare namespace AuthTokensOrgAttributes {
    interface Raw {
        display_id: string;
        id: string;
        slug?: string | null;
    }
}
