/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const ClientContextDevice: core.serialization.ObjectSchema<
    serializers.ClientContextDevice.Raw,
    DevRev.ClientContextDevice
> = core.serialization.object({
    type: core.serialization.string().optional(),
    manufacturer: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
});

export declare namespace ClientContextDevice {
    interface Raw {
        type?: string | null;
        manufacturer?: string | null;
        model?: string | null;
    }
}
