/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const ClientContextBrowser: core.serialization.ObjectSchema<
    serializers.ClientContextBrowser.Raw,
    DevRev.ClientContextBrowser
> = core.serialization.object({
    name: core.serialization.string().optional(),
    version: core.serialization.string().optional(),
});

export declare namespace ClientContextBrowser {
    interface Raw {
        name?: string | null;
        version?: string | null;
    }
}
