/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { CodeChange } from "./CodeChange";

export const CodeChangesListResponse: core.serialization.ObjectSchema<
    serializers.CodeChangesListResponse.Raw,
    DevRev.CodeChangesListResponse
> = core.serialization.object({
    codeChanges: core.serialization.property("code_changes", core.serialization.list(CodeChange)),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
});

export declare namespace CodeChangesListResponse {
    interface Raw {
        code_changes: CodeChange.Raw[];
        next_cursor?: string | null;
        prev_cursor?: string | null;
    }
}
