/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Conversation } from "./Conversation";

export const ConversationsCreateResponse: core.serialization.ObjectSchema<
    serializers.ConversationsCreateResponse.Raw,
    DevRev.ConversationsCreateResponse
> = core.serialization.object({
    conversation: Conversation,
});

export declare namespace ConversationsCreateResponse {
    interface Raw {
        conversation: Conversation.Raw;
    }
}
