/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const ConversationsCreateRequestTypeValue: core.serialization.Schema<
    serializers.ConversationsCreateRequestTypeValue.Raw,
    DevRev.ConversationsCreateRequestTypeValue
> = core.serialization.stringLiteral("support");

export declare namespace ConversationsCreateRequestTypeValue {
    type Raw = "support";
}
