/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { VistaBaseSummary } from "./VistaBaseSummary";

export const CuratedVistaSummary: core.serialization.ObjectSchema<
    serializers.CuratedVistaSummary.Raw,
    DevRev.CuratedVistaSummary
> = VistaBaseSummary;

export declare namespace CuratedVistaSummary {
    type Raw = VistaBaseSummary.Raw;
}
