/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { AtomBaseSummary } from "./AtomBaseSummary";

export const CustomStateSummary: core.serialization.ObjectSchema<
    serializers.CustomStateSummary.Raw,
    DevRev.CustomStateSummary
> = core.serialization
    .object({
        isFinal: core.serialization.property("is_final", core.serialization.boolean().optional()),
        name: core.serialization.string().optional(),
    })
    .extend(AtomBaseSummary);

export declare namespace CustomStateSummary {
    interface Raw extends AtomBaseSummary.Raw {
        is_final?: boolean | null;
        name?: string | null;
    }
}
