/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { CustomState } from "./CustomState";

export const CustomStatesListResponse: core.serialization.ObjectSchema<
    serializers.CustomStatesListResponse.Raw,
    DevRev.CustomStatesListResponse
> = core.serialization.object({
    cursor: core.serialization.string().optional(),
    result: core.serialization.list(CustomState),
});

export declare namespace CustomStatesListResponse {
    interface Raw {
        cursor?: string | null;
        result: CustomState.Raw[];
    }
}
