/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { CustomTypePathComponent } from "./CustomTypePathComponent";
import { StockFieldOverride } from "./StockFieldOverride";

export const CustomSchemaFragmentsSetRequestCustomTypeFragment: core.serialization.ObjectSchema<
    serializers.CustomSchemaFragmentsSetRequestCustomTypeFragment.Raw,
    DevRev.CustomSchemaFragmentsSetRequestCustomTypeFragment
> = core.serialization.object({
    path: core.serialization.list(CustomTypePathComponent).optional(),
    stageDiagram: core.serialization.property("stage_diagram", core.serialization.string().optional()),
    stockFieldOverrides: core.serialization.property(
        "stock_field_overrides",
        core.serialization.list(StockFieldOverride).optional()
    ),
    subtype: core.serialization.string(),
    subtypeDisplayName: core.serialization.property("subtype_display_name", core.serialization.string().optional()),
});

export declare namespace CustomSchemaFragmentsSetRequestCustomTypeFragment {
    interface Raw {
        path?: CustomTypePathComponent.Raw[] | null;
        stage_diagram?: string | null;
        stock_field_overrides?: StockFieldOverride.Raw[] | null;
        subtype: string;
        subtype_display_name?: string | null;
    }
}
