/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const CustomSchemaFragmentFragmentType: core.serialization.Schema<
    serializers.CustomSchemaFragmentFragmentType.Raw,
    DevRev.CustomSchemaFragmentFragmentType
> = core.serialization.enum_(["app", "custom_type", "tenant"]);

export declare namespace CustomSchemaFragmentFragmentType {
    type Raw = "app" | "custom_type" | "tenant";
}
