/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { CustomObjectSummary } from "./CustomObjectSummary";
import { SearchSummaryBase } from "./SearchSummaryBase";

export const CustomObjectSearchSummary: core.serialization.ObjectSchema<
    serializers.CustomObjectSearchSummary.Raw,
    DevRev.CustomObjectSearchSummary
> = core.serialization
    .object({
        customObject: core.serialization.property("custom_object", CustomObjectSummary),
    })
    .extend(SearchSummaryBase);

export declare namespace CustomObjectSearchSummary {
    interface Raw extends SearchSummaryBase.Raw {
        custom_object: CustomObjectSummary.Raw;
    }
}
