/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const DateTimeFilter: core.serialization.ObjectSchema<serializers.DateTimeFilter.Raw, DevRev.DateTimeFilter> =
    core.serialization.object({
        after: core.serialization.date().optional(),
        before: core.serialization.date().optional(),
    });

export declare namespace DateTimeFilter {
    interface Raw {
        after?: string | null;
        before?: string | null;
    }
}
