/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { AuthConnection } from "./AuthConnection";

export const DevOrgAuthConnectionsListResponse: core.serialization.ObjectSchema<
    serializers.DevOrgAuthConnectionsListResponse.Raw,
    DevRev.DevOrgAuthConnectionsListResponse
> = core.serialization.object({
    authConnections: core.serialization.property("auth_connections", core.serialization.list(AuthConnection)),
});

export declare namespace DevOrgAuthConnectionsListResponse {
    interface Raw {
        auth_connections: AuthConnection.Raw[];
    }
}
