/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const DevOrgAuthConnectionsCreateRequestGoogleAppsOptions: core.serialization.ObjectSchema<
    serializers.DevOrgAuthConnectionsCreateRequestGoogleAppsOptions.Raw,
    DevRev.DevOrgAuthConnectionsCreateRequestGoogleAppsOptions
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string()),
    tenantDomain: core.serialization.property("tenant_domain", core.serialization.string()),
});

export declare namespace DevOrgAuthConnectionsCreateRequestGoogleAppsOptions {
    interface Raw {
        client_id: string;
        client_secret: string;
        tenant_domain: string;
    }
}
