/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { UserBaseSummary } from "./UserBaseSummary";

export const DevUserSummary: core.serialization.ObjectSchema<serializers.DevUserSummary.Raw, DevRev.DevUserSummary> =
    UserBaseSummary;

export declare namespace DevUserSummary {
    type Raw = UserBaseSummary.Raw;
}
