/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const DevUserExternalIdentityFilter: core.serialization.ObjectSchema<
    serializers.DevUserExternalIdentityFilter.Raw,
    DevRev.DevUserExternalIdentityFilter
> = core.serialization.object({
    id: core.serialization.string().optional(),
    issuer: core.serialization.string().optional(),
});

export declare namespace DevUserExternalIdentityFilter {
    interface Raw {
        id?: string | null;
        issuer?: string | null;
    }
}
