/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { UserSummary } from "./UserSummary";

export const EmailInfo: core.serialization.ObjectSchema<serializers.EmailInfo.Raw, DevRev.EmailInfo> =
    core.serialization.object({
        address: core.serialization.string(),
        name: core.serialization.string().optional(),
        user: UserSummary.optional(),
    });

export declare namespace EmailInfo {
    interface Raw {
        address: string;
        name?: string | null;
        user?: UserSummary.Raw | null;
    }
}
