/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const EngagementsCountResponse: core.serialization.ObjectSchema<
    serializers.EngagementsCountResponse.Raw,
    DevRev.EngagementsCountResponse
> = core.serialization.object({
    count: core.serialization.number(),
});

export declare namespace EngagementsCountResponse {
    interface Raw {
        count: number;
    }
}
