/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const EnumValueSummary: core.serialization.ObjectSchema<
    serializers.EnumValueSummary.Raw,
    DevRev.EnumValueSummary
> = core.serialization.object({
    id: core.serialization.number(),
    label: core.serialization.string(),
    ordinal: core.serialization.number(),
});

export declare namespace EnumValueSummary {
    interface Raw {
        id: number;
        label: string;
        ordinal: number;
    }
}
