/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { ErrorBase } from "./ErrorBase";

export const ErrorTooManyRequests: core.serialization.ObjectSchema<
    serializers.ErrorTooManyRequests.Raw,
    DevRev.ErrorTooManyRequests
> = core.serialization.object({}).extend(ErrorBase);

export declare namespace ErrorTooManyRequests {
    interface Raw extends ErrorBase.Raw {}
}
