/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const Error_: core.serialization.ObjectSchema<serializers.Error_.Raw, DevRev.Error_> = core.serialization.object(
    {
        type: core.serialization.string().optional(),
        message: core.serialization.string(),
        status: core.serialization.number(),
    }
);

export declare namespace Error_ {
    interface Raw {
        type?: string | null;
        message: string;
        status: number;
    }
}
