/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { ErrorBase } from "./ErrorBase";

export const ErrorForbidden: core.serialization.ObjectSchema<serializers.ErrorForbidden.Raw, DevRev.ErrorForbidden> =
    core.serialization.object({}).extend(ErrorBase);

export declare namespace ErrorForbidden {
    interface Raw extends ErrorBase.Raw {}
}
