/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const EventSourceSetupInstructions: core.serialization.ObjectSchema<
    serializers.EventSourceSetupInstructions.Raw,
    DevRev.EventSourceSetupInstructions
> = core.serialization.object({
    content: core.serialization.string().optional(),
});

export declare namespace EventSourceSetupInstructions {
    interface Raw {
        content?: string | null;
    }
}
