/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const FieldValueInt64List: core.serialization.ObjectSchema<
    serializers.FieldValueInt64List.Raw,
    DevRev.FieldValueInt64List
> = core.serialization.object({
    values: core.serialization.list(core.serialization.number()),
});

export declare namespace FieldValueInt64List {
    interface Raw {
        values: number[];
    }
}
