/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const FieldValueId: core.serialization.ObjectSchema<serializers.FieldValueId.Raw, DevRev.FieldValueId> =
    core.serialization.object({
        value: core.serialization.string(),
    });

export declare namespace FieldValueId {
    interface Raw {
        value: string;
    }
}
