/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Incident } from "./Incident";

export const IncidentsGetResponse: core.serialization.ObjectSchema<
    serializers.IncidentsGetResponse.Raw,
    DevRev.IncidentsGetResponse
> = core.serialization.object({
    incident: Incident,
});

export declare namespace IncidentsGetResponse {
    interface Raw {
        incident: Incident.Raw;
    }
}
