/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Link } from "./Link";

export const LinksListResponse: core.serialization.ObjectSchema<
    serializers.LinksListResponse.Raw,
    DevRev.LinksListResponse
> = core.serialization.object({
    links: core.serialization.list(Link),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
});

export declare namespace LinksListResponse {
    interface Raw {
        links: Link.Raw[];
        next_cursor?: string | null;
        prev_cursor?: string | null;
    }
}
