/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Meeting } from "./Meeting";

export const MeetingsListResponse: core.serialization.ObjectSchema<
    serializers.MeetingsListResponse.Raw,
    DevRev.MeetingsListResponse
> = core.serialization.object({
    meetings: core.serialization.list(Meeting),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
});

export declare namespace MeetingsListResponse {
    interface Raw {
        meetings: Meeting.Raw[];
        next_cursor?: string | null;
        prev_cursor?: string | null;
    }
}
