/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const MetricDefinitionMetricType: core.serialization.Schema<
    serializers.MetricDefinitionMetricType.Raw,
    DevRev.MetricDefinitionMetricType
> = core.serialization.enum_(["time", "value"]);

export declare namespace MetricDefinitionMetricType {
    type Raw = "time" | "value";
}
