/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { AtomBaseSummary } from "./AtomBaseSummary";

export const MetricDefinitionSummary: core.serialization.ObjectSchema<
    serializers.MetricDefinitionSummary.Raw,
    DevRev.MetricDefinitionSummary
> = core.serialization
    .object({
        name: core.serialization.string().optional(),
    })
    .extend(AtomBaseSummary);

export declare namespace MetricDefinitionSummary {
    interface Raw extends AtomBaseSummary.Raw {
        name?: string | null;
    }
}
