/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const MetricActionExecuteRequestAction: core.serialization.Schema<
    serializers.MetricActionExecuteRequestAction.Raw,
    DevRev.MetricActionExecuteRequestAction
> = core.serialization.enum_(["complete", "pause", "restart", "resume", "start"]);

export declare namespace MetricActionExecuteRequestAction {
    type Raw = "complete" | "pause" | "restart" | "resume" | "start";
}
