/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { OrgScheduleFragment } from "./OrgScheduleFragment";

export const OrgScheduleFragmentsTransitionResponse: core.serialization.ObjectSchema<
    serializers.OrgScheduleFragmentsTransitionResponse.Raw,
    DevRev.OrgScheduleFragmentsTransitionResponse
> = core.serialization.object({
    orgScheduleFragment: core.serialization.property("org_schedule_fragment", OrgScheduleFragment),
});

export declare namespace OrgScheduleFragmentsTransitionResponse {
    interface Raw {
        org_schedule_fragment: OrgScheduleFragment.Raw;
    }
}
