/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const OrgScheduleFragmentStatus: core.serialization.Schema<
    serializers.OrgScheduleFragmentStatus.Raw,
    DevRev.OrgScheduleFragmentStatus
> = core.serialization.enum_(["archived", "draft", "published"]);

export declare namespace OrgScheduleFragmentStatus {
    type Raw = "archived" | "draft" | "published";
}
