/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const PartsCreateRequestFeature: core.serialization.ObjectSchema<
    serializers.PartsCreateRequestFeature.Raw,
    DevRev.PartsCreateRequestFeature
> = core.serialization.object({
    parentPart: core.serialization.property("parent_part", core.serialization.list(core.serialization.string())),
});

export declare namespace PartsCreateRequestFeature {
    interface Raw {
        parent_part: string[];
    }
}
