/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Part } from "./Part";

export const PartsUpdateResponse: core.serialization.ObjectSchema<
    serializers.PartsUpdateResponse.Raw,
    DevRev.PartsUpdateResponse
> = core.serialization.object({
    part: Part,
});

export declare namespace PartsUpdateResponse {
    interface Raw {
        part: Part.Raw;
    }
}
