/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Part } from "./Part";

export const PartsCreateResponse: core.serialization.ObjectSchema<
    serializers.PartsCreateResponse.Raw,
    DevRev.PartsCreateResponse
> = core.serialization.object({
    part: Part,
});

export declare namespace PartsCreateResponse {
    interface Raw {
        part: Part.Raw;
    }
}
