/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { CommentSearchSummary } from "./CommentSearchSummary";
import { PartSummary } from "./PartSummary";
import { SearchSummaryBase } from "./SearchSummaryBase";

export const PartSearchSummary: core.serialization.ObjectSchema<
    serializers.PartSearchSummary.Raw,
    DevRev.PartSearchSummary
> = core.serialization
    .object({
        comments: core.serialization.list(CommentSearchSummary).optional(),
        part: PartSummary,
    })
    .extend(SearchSummaryBase);

export declare namespace PartSearchSummary {
    interface Raw extends SearchSummaryBase.Raw {
        comments?: CommentSearchSummary.Raw[] | null;
        part: PartSummary.Raw;
    }
}
