/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { QuestionAnswer } from "./QuestionAnswer";

export const QuestionAnswersCreateResponse: core.serialization.ObjectSchema<
    serializers.QuestionAnswersCreateResponse.Raw,
    DevRev.QuestionAnswersCreateResponse
> = core.serialization.object({
    questionAnswer: core.serialization.property("question_answer", QuestionAnswer),
});

export declare namespace QuestionAnswersCreateResponse {
    interface Raw {
        question_answer: QuestionAnswer.Raw;
    }
}
