/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { AtomBaseSummary } from "./AtomBaseSummary";

export const QuestionAnswerSummary: core.serialization.ObjectSchema<
    serializers.QuestionAnswerSummary.Raw,
    DevRev.QuestionAnswerSummary
> = core.serialization
    .object({
        question: core.serialization.string().optional(),
    })
    .extend(AtomBaseSummary);

export declare namespace QuestionAnswerSummary {
    interface Raw extends AtomBaseSummary.Raw {
        question?: string | null;
    }
}
