/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { RevOrg } from "./RevOrg";

export const RevOrgsListResponse: core.serialization.ObjectSchema<
    serializers.RevOrgsListResponse.Raw,
    DevRev.RevOrgsListResponse
> = core.serialization.object({
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
    revOrgs: core.serialization.property("rev_orgs", core.serialization.list(RevOrg)),
});

export declare namespace RevOrgsListResponse {
    interface Raw {
        next_cursor?: string | null;
        prev_cursor?: string | null;
        rev_orgs: RevOrg.Raw[];
    }
}
