/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { RevUser } from "./RevUser";

export const RevUsersListResponse: core.serialization.ObjectSchema<
    serializers.RevUsersListResponse.Raw,
    DevRev.RevUsersListResponse
> = core.serialization.object({
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
    prevCursor: core.serialization.property("prev_cursor", core.serialization.string().optional()),
    revUsers: core.serialization.property("rev_users", core.serialization.list(RevUser)),
});

export declare namespace RevUsersListResponse {
    interface Raw {
        next_cursor?: string | null;
        prev_cursor?: string | null;
        rev_users: RevUser.Raw[];
    }
}
