/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { SchemaFieldDescriptorBase } from "./SchemaFieldDescriptorBase";

export const SchemaUnknownFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaUnknownFieldDescriptor.Raw,
    DevRev.SchemaUnknownFieldDescriptor
> = SchemaFieldDescriptorBase;

export declare namespace SchemaUnknownFieldDescriptor {
    type Raw = SchemaFieldDescriptorBase.Raw;
}
