/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SchemaFieldOasisMetadata: core.serialization.Schema<
    serializers.SchemaFieldOasisMetadata.Raw,
    DevRev.SchemaFieldOasisMetadata
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace SchemaFieldOasisMetadata {
    type Raw = Record<string, unknown>;
}
