/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SchemaFieldListViewUiMetadata: core.serialization.ObjectSchema<
    serializers.SchemaFieldListViewUiMetadata.Raw,
    DevRev.SchemaFieldListViewUiMetadata
> = core.serialization.object({
    isHidden: core.serialization.property("is_hidden", core.serialization.boolean().optional()),
});

export declare namespace SchemaFieldListViewUiMetadata {
    interface Raw {
        is_hidden?: boolean | null;
    }
}
