/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { SchemaFieldDescriptorBase } from "./SchemaFieldDescriptorBase";

export const SchemaIdFieldDescriptor: core.serialization.ObjectSchema<
    serializers.SchemaIdFieldDescriptor.Raw,
    DevRev.SchemaIdFieldDescriptor
> = core.serialization
    .object({
        defaultValue: core.serialization.property("default_value", core.serialization.string().optional()),
        idType: core.serialization.property("id_type", core.serialization.list(core.serialization.string()).optional()),
    })
    .extend(SchemaFieldDescriptorBase);

export declare namespace SchemaIdFieldDescriptor {
    interface Raw extends SchemaFieldDescriptorBase.Raw {
        default_value?: string | null;
        id_type?: string[] | null;
    }
}
