/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { SearchResult } from "./SearchResult";

export const SearchCoreResponse: core.serialization.ObjectSchema<
    serializers.SearchCoreResponse.Raw,
    DevRev.SearchCoreResponse
> = core.serialization.object({
    cursor: core.serialization.string().optional(),
    results: core.serialization.list(SearchResult),
});

export declare namespace SearchCoreResponse {
    interface Raw {
        cursor?: string | null;
        results: SearchResult.Raw[];
    }
}
