/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { AccountSearchSummary } from "./AccountSearchSummary";
import { ArticleSearchSummary } from "./ArticleSearchSummary";
import { ArtifactSearchSummary } from "./ArtifactSearchSummary";
import { ConversationSearchSummary } from "./ConversationSearchSummary";
import { CustomObjectSearchSummary } from "./CustomObjectSearchSummary";
import { DashboardSearchSummary } from "./DashboardSearchSummary";
import { GroupSearchSummary } from "./GroupSearchSummary";
import { LinkSearchSummary } from "./LinkSearchSummary";
import { ObjectMemberSearchSummary } from "./ObjectMemberSearchSummary";
import { OrgSearchSummary } from "./OrgSearchSummary";
import { PartSearchSummary } from "./PartSearchSummary";
import { QuestionAnswerSearchSummary } from "./QuestionAnswerSearchSummary";
import { TagSearchSummary } from "./TagSearchSummary";
import { UserSearchSummary } from "./UserSearchSummary";
import { VistaSearchSummary } from "./VistaSearchSummary";
import { WorkSearchSummary } from "./WorkSearchSummary";

export const SearchResult: core.serialization.Schema<serializers.SearchResult.Raw, DevRev.SearchResult> =
    core.serialization
        .union("type", {
            account: AccountSearchSummary,
            article: ArticleSearchSummary,
            artifact: ArtifactSearchSummary,
            conversation: ConversationSearchSummary,
            custom_object: CustomObjectSearchSummary,
            dashboard: DashboardSearchSummary,
            group: GroupSearchSummary,
            link: LinkSearchSummary,
            object_member: ObjectMemberSearchSummary,
            org: OrgSearchSummary,
            part: PartSearchSummary,
            question_answer: QuestionAnswerSearchSummary,
            tag: TagSearchSummary,
            user: UserSearchSummary,
            vista: VistaSearchSummary,
            work: WorkSearchSummary,
        })
        .transform<DevRev.SearchResult>({
            transform: (value) => value,
            untransform: (value) => value,
        });

export declare namespace SearchResult {
    type Raw =
        | SearchResult.Account
        | SearchResult.Article
        | SearchResult.Artifact
        | SearchResult.Conversation
        | SearchResult.CustomObject
        | SearchResult.Dashboard
        | SearchResult.Group
        | SearchResult.Link
        | SearchResult.ObjectMember
        | SearchResult.Org
        | SearchResult.Part
        | SearchResult.QuestionAnswer
        | SearchResult.Tag
        | SearchResult.User
        | SearchResult.Vista
        | SearchResult.Work;

    interface Account extends AccountSearchSummary.Raw {
        type: "account";
    }

    interface Article extends ArticleSearchSummary.Raw {
        type: "article";
    }

    interface Artifact extends ArtifactSearchSummary.Raw {
        type: "artifact";
    }

    interface Conversation extends ConversationSearchSummary.Raw {
        type: "conversation";
    }

    interface CustomObject extends CustomObjectSearchSummary.Raw {
        type: "custom_object";
    }

    interface Dashboard extends DashboardSearchSummary.Raw {
        type: "dashboard";
    }

    interface Group extends GroupSearchSummary.Raw {
        type: "group";
    }

    interface Link extends LinkSearchSummary.Raw {
        type: "link";
    }

    interface ObjectMember extends ObjectMemberSearchSummary.Raw {
        type: "object_member";
    }

    interface Org extends OrgSearchSummary.Raw {
        type: "org";
    }

    interface Part extends PartSearchSummary.Raw {
        type: "part";
    }

    interface QuestionAnswer extends QuestionAnswerSearchSummary.Raw {
        type: "question_answer";
    }

    interface Tag extends TagSearchSummary.Raw {
        type: "tag";
    }

    interface User extends UserSearchSummary.Raw {
        type: "user";
    }

    interface Vista extends VistaSearchSummary.Raw {
        type: "vista";
    }

    interface Work extends WorkSearchSummary.Raw {
        type: "work";
    }
}
