/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SearchSortOrderParam: core.serialization.Schema<
    serializers.SearchSortOrderParam.Raw,
    DevRev.SearchSortOrderParam
> = core.serialization.enum_(["asc", "desc"]);

export declare namespace SearchSortOrderParam {
    type Raw = "asc" | "desc";
}
