/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SearchSortByParam: core.serialization.Schema<serializers.SearchSortByParam.Raw, DevRev.SearchSortByParam> =
    core.serialization.enum_(["created_date", "modified_date", "relevance"]);

export declare namespace SearchSortByParam {
    type Raw = "created_date" | "modified_date" | "relevance";
}
