/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SearchNamespace: core.serialization.Schema<serializers.SearchNamespace.Raw, DevRev.SearchNamespace> =
    core.serialization.enum_([
        "account",
        "article",
        "capability",
        "component",
        "conversation",
        "custom_object",
        "custom_part",
        "custom_work",
        "dashboard",
        "dev_user",
        "enhancement",
        "feature",
        "group",
        "issue",
        "linkable",
        "microservice",
        "object_member",
        "opportunity",
        "product",
        "project",
        "question_answer",
        "rev_org",
        "rev_user",
        "runnable",
        "service_account",
        "sys_user",
        "tag",
        "task",
        "ticket",
        "vista",
    ]);

export declare namespace SearchNamespace {
    type Raw =
        | "account"
        | "article"
        | "capability"
        | "component"
        | "conversation"
        | "custom_object"
        | "custom_part"
        | "custom_work"
        | "dashboard"
        | "dev_user"
        | "enhancement"
        | "feature"
        | "group"
        | "issue"
        | "linkable"
        | "microservice"
        | "object_member"
        | "opportunity"
        | "product"
        | "project"
        | "question_answer"
        | "rev_org"
        | "rev_user"
        | "runnable"
        | "service_account"
        | "sys_user"
        | "tag"
        | "task"
        | "ticket"
        | "vista";
}
