/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { ServiceAccount } from "./ServiceAccount";

export const ServiceAccountsGetResponse: core.serialization.ObjectSchema<
    serializers.ServiceAccountsGetResponse.Raw,
    DevRev.ServiceAccountsGetResponse
> = core.serialization.object({
    serviceAccount: core.serialization.property("service_account", ServiceAccount),
});

export declare namespace ServiceAccountsGetResponse {
    interface Raw {
        service_account: ServiceAccount.Raw;
    }
}
