/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SetOrgScheduleFragmentSummary: core.serialization.ObjectSchema<
    serializers.SetOrgScheduleFragmentSummary.Raw,
    DevRev.SetOrgScheduleFragmentSummary
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace SetOrgScheduleFragmentSummary {
    interface Raw {
        id: string;
    }
}
