/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SetSupportMetricTarget: core.serialization.ObjectSchema<
    serializers.SetSupportMetricTarget.Raw,
    DevRev.SetSupportMetricTarget
> = core.serialization.object({
    metric: core.serialization.string(),
    orgScheduleId: core.serialization.property("org_schedule_id", core.serialization.string().optional()),
    performance: core.serialization.number().optional(),
    target: core.serialization.number(),
    warningTarget: core.serialization.property("warning_target", core.serialization.number().optional()),
});

export declare namespace SetSupportMetricTarget {
    interface Raw {
        metric: string;
        org_schedule_id?: string | null;
        performance?: number | null;
        target: number;
        warning_target?: number | null;
    }
}
