/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { SetSupportMetricTarget } from "./SetSupportMetricTarget";
import { SetSlaSelector } from "./SetSlaSelector";

export const SetSlaPolicy: core.serialization.ObjectSchema<serializers.SetSlaPolicy.Raw, DevRev.SetSlaPolicy> =
    core.serialization.object({
        metrics: core.serialization.list(SetSupportMetricTarget).optional(),
        name: core.serialization.string(),
        selector: SetSlaSelector,
    });

export declare namespace SetSlaPolicy {
    interface Raw {
        metrics?: SetSupportMetricTarget.Raw[] | null;
        name: string;
        selector: SetSlaSelector.Raw;
    }
}
