/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SlaPolicy: core.serialization.Schema<serializers.SlaPolicy.Raw, DevRev.SlaPolicy> =
    core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace SlaPolicy {
    type Raw = Record<string, unknown>;
}
