/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Sla } from "./Sla";

export const SlasCreateResponse: core.serialization.ObjectSchema<
    serializers.SlasCreateResponse.Raw,
    DevRev.SlasCreateResponse
> = core.serialization.object({
    sla: Sla,
});

export declare namespace SlasCreateResponse {
    interface Raw {
        sla: Sla.Raw;
    }
}
