/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const StageFilter: core.serialization.ObjectSchema<serializers.StageFilter.Raw, DevRev.StageFilter> =
    core.serialization.object({
        name: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace StageFilter {
    interface Raw {
        name?: string[] | null;
    }
}
