/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { StockSchemaFragment } from "./StockSchemaFragment";

export const StockSchemaFragmentsGetResponse: core.serialization.ObjectSchema<
    serializers.StockSchemaFragmentsGetResponse.Raw,
    DevRev.StockSchemaFragmentsGetResponse
> = core.serialization.object({
    fragment: StockSchemaFragment,
});

export declare namespace StockSchemaFragmentsGetResponse {
    interface Raw {
        fragment: StockSchemaFragment.Raw;
    }
}
