/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SyncProgressState: core.serialization.Schema<serializers.SyncProgressState.Raw, DevRev.SyncProgressState> =
    core.serialization.enum_([
        "completed",
        "delete_in_progress",
        "deleted",
        "deletion_error",
        "extract_attachments",
        "extract_attachments_error",
        "extraction",
        "extraction_error",
        "loading",
        "loading_attachments",
        "loading_attachments_error",
        "loading_error",
        "recipe_discovery",
        "recipe_discovery_error",
        "recipe_discovery_waiting_for_user_input",
        "starting",
        "transformation",
        "transformation_error",
    ]);

export declare namespace SyncProgressState {
    type Raw =
        | "completed"
        | "delete_in_progress"
        | "deleted"
        | "deletion_error"
        | "extract_attachments"
        | "extract_attachments_error"
        | "extraction"
        | "extraction_error"
        | "loading"
        | "loading_attachments"
        | "loading_attachments_error"
        | "loading_error"
        | "recipe_discovery"
        | "recipe_discovery_error"
        | "recipe_discovery_waiting_for_user_input"
        | "starting"
        | "transformation"
        | "transformation_error";
}
