/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SyncMetadataFilterSyncInFilterStatus: core.serialization.Schema<
    serializers.SyncMetadataFilterSyncInFilterStatus.Raw,
    DevRev.SyncMetadataFilterSyncInFilterStatus
> = core.serialization.enum_(["failed", "modified", "staged", "succeeded"]);

export declare namespace SyncMetadataFilterSyncInFilterStatus {
    type Raw = "failed" | "modified" | "staged" | "succeeded";
}
