/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const SyncMetadataFilterSyncOutFilterStatus: core.serialization.Schema<
    serializers.SyncMetadataFilterSyncOutFilterStatus.Raw,
    DevRev.SyncMetadataFilterSyncOutFilterStatus
> = core.serialization.enum_(["failed", "modified", "succeeded"]);

export declare namespace SyncMetadataFilterSyncOutFilterStatus {
    type Raw = "failed" | "modified" | "succeeded";
}
