/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { TimelineEntryBaseSummary } from "./TimelineEntryBaseSummary";

export const TimelineChangeEventSummary: core.serialization.ObjectSchema<
    serializers.TimelineChangeEventSummary.Raw,
    DevRev.TimelineChangeEventSummary
> = TimelineEntryBaseSummary;

export declare namespace TimelineChangeEventSummary {
    type Raw = TimelineEntryBaseSummary.Raw;
}
