/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const TimelineEntriesDeleteResponse: core.serialization.Schema<
    serializers.TimelineEntriesDeleteResponse.Raw,
    DevRev.TimelineEntriesDeleteResponse
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace TimelineEntriesDeleteResponse {
    type Raw = Record<string, unknown>;
}
