/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const TimelineEntryVisibility: core.serialization.Schema<
    serializers.TimelineEntryVisibility.Raw,
    DevRev.TimelineEntryVisibility
> = core.serialization.enum_(["external", "internal", "private", "public"]);

export declare namespace TimelineEntryVisibility {
    type Raw = "external" | "internal" | "private" | "public";
}
