/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { LinkSummary } from "./LinkSummary";

export const TimelineChangeEventLinked: core.serialization.ObjectSchema<
    serializers.TimelineChangeEventLinked.Raw,
    DevRev.TimelineChangeEventLinked
> = core.serialization.object({
    link: LinkSummary.optional(),
});

export declare namespace TimelineChangeEventLinked {
    interface Raw {
        link?: LinkSummary.Raw | null;
    }
}
