/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const UomsUpdateRequestDimensions: core.serialization.ObjectSchema<
    serializers.UomsUpdateRequestDimensions.Raw,
    DevRev.UomsUpdateRequestDimensions
> = core.serialization.object({
    add: core.serialization.list(core.serialization.string()).optional(),
    remove: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace UomsUpdateRequestDimensions {
    interface Raw {
        add?: string[] | null;
        remove?: string[] | null;
    }
}
