/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const UpdateIncidentRelatedDocs: core.serialization.ObjectSchema<
    serializers.UpdateIncidentRelatedDocs.Raw,
    DevRev.UpdateIncidentRelatedDocs
> = core.serialization.object({
    set: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace UpdateIncidentRelatedDocs {
    interface Raw {
        set?: string[] | null;
    }
}
