/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { PreferencesBaseSummary } from "./PreferencesBaseSummary";

export const UserPreferencesSummary: core.serialization.ObjectSchema<
    serializers.UserPreferencesSummary.Raw,
    DevRev.UserPreferencesSummary
> = PreferencesBaseSummary;

export declare namespace UserPreferencesSummary {
    type Raw = PreferencesBaseSummary.Raw;
}
