/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const UserType: core.serialization.Schema<serializers.UserType.Raw, DevRev.UserType> = core.serialization.enum_([
    "dev_user",
    "rev_user",
    "service_account",
    "sys_user",
]);

export declare namespace UserType {
    type Raw = "dev_user" | "rev_user" | "service_account" | "sys_user";
}
