/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { AtomBaseSummary } from "./AtomBaseSummary";

export const VistaBaseSummary: core.serialization.ObjectSchema<
    serializers.VistaBaseSummary.Raw,
    DevRev.VistaBaseSummary
> = core.serialization
    .object({
        name: core.serialization.string(),
    })
    .extend(AtomBaseSummary);

export declare namespace VistaBaseSummary {
    interface Raw extends AtomBaseSummary.Raw {
        name: string;
    }
}
