/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { AtomBaseSummary } from "./AtomBaseSummary";

export const WebhookSummary: core.serialization.ObjectSchema<serializers.WebhookSummary.Raw, DevRev.WebhookSummary> =
    AtomBaseSummary;

export declare namespace WebhookSummary {
    type Raw = AtomBaseSummary.Raw;
}
