/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";
import { Webhook } from "./Webhook";

export const WebhooksUpdateResponse: core.serialization.ObjectSchema<
    serializers.WebhooksUpdateResponse.Raw,
    DevRev.WebhooksUpdateResponse
> = core.serialization.object({
    webhook: Webhook,
});

export declare namespace WebhooksUpdateResponse {
    interface Raw {
        webhook: Webhook.Raw;
    }
}
