/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index";
import * as DevRev from "../../api/index";
import * as core from "../../core";

export const WorksDeleteResponse: core.serialization.Schema<
    serializers.WorksDeleteResponse.Raw,
    DevRev.WorksDeleteResponse
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace WorksDeleteResponse {
    type Raw = Record<string, unknown>;
}
