/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";
import { SetWeeklyOrgSchedule } from "../../../../types/SetWeeklyOrgSchedule";
import { SetOrgScheduleFragmentSummary } from "../../../../types/SetOrgScheduleFragmentSummary";

export const OrgSchedulesUpdateRequest: core.serialization.Schema<
    serializers.OrgSchedulesUpdateRequest.Raw,
    DevRev.OrgSchedulesUpdateRequest
> = core.serialization.object({
    defaultWeeklyOrgSchedule: core.serialization.property(
        "default_weekly_org_schedule",
        SetWeeklyOrgSchedule.optional()
    ),
    id: core.serialization.string(),
    minValidDays: core.serialization.property("min_valid_days", core.serialization.number().optional()),
    name: core.serialization.string().optional(),
    orgScheduleFragments: core.serialization.property(
        "org_schedule_fragments",
        core.serialization.list(SetOrgScheduleFragmentSummary).optional()
    ),
    timezone: core.serialization.string().optional(),
    weeklyOrgSchedules: core.serialization.property(
        "weekly_org_schedules",
        core.serialization.list(SetWeeklyOrgSchedule).optional()
    ),
});

export declare namespace OrgSchedulesUpdateRequest {
    interface Raw {
        default_weekly_org_schedule?: SetWeeklyOrgSchedule.Raw | null;
        id: string;
        min_valid_days?: number | null;
        name?: string | null;
        org_schedule_fragments?: SetOrgScheduleFragmentSummary.Raw[] | null;
        timezone?: string | null;
        weekly_org_schedules?: SetWeeklyOrgSchedule.Raw[] | null;
    }
}
