/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const OrgScheduleFragmentsGetRequest: core.serialization.Schema<
    serializers.OrgScheduleFragmentsGetRequest.Raw,
    DevRev.OrgScheduleFragmentsGetRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace OrgScheduleFragmentsGetRequest {
    interface Raw {
        id: string;
    }
}
