/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";

export const MetricDefinitionsDeleteRequest: core.serialization.Schema<
    serializers.MetricDefinitionsDeleteRequest.Raw,
    DevRev.MetricDefinitionsDeleteRequest
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace MetricDefinitionsDeleteRequest {
    interface Raw {
        id: string;
    }
}
