/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";
import { MetricActionExecuteRequestAction } from "../../../../types/MetricActionExecuteRequestAction";

export const MetricActionExecuteRequest: core.serialization.Schema<
    serializers.MetricActionExecuteRequest.Raw,
    DevRev.MetricActionExecuteRequest
> = core.serialization.object({
    action: MetricActionExecuteRequestAction,
    eventDate: core.serialization.property("event_date", core.serialization.date()),
    metric: core.serialization.string(),
    object: core.serialization.string(),
});

export declare namespace MetricActionExecuteRequest {
    interface Raw {
        action: MetricActionExecuteRequestAction.Raw;
        event_date: string;
        metric: string;
        object: string;
    }
}
