/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index";
import * as DevRev from "../../../../../api/index";
import * as core from "../../../../../core";
import { DateTimeFilter } from "../../../../types/DateTimeFilter";
import { ListMode } from "../../../../types/ListMode";

export const SlaTrackersListRequest: core.serialization.Schema<
    serializers.SlaTrackersListRequest.Raw,
    DevRev.SlaTrackersListRequest
> = core.serialization.object({
    createdDate: core.serialization.property("created_date", DateTimeFilter.optional()),
    cursor: core.serialization.string().optional(),
    limit: core.serialization.number().optional(),
    mode: ListMode.optional(),
    modifiedDate: core.serialization.property("modified_date", DateTimeFilter.optional()),
    sortBy: core.serialization.property("sort_by", core.serialization.list(core.serialization.string()).optional()),
    stage: core.serialization.list(core.serialization.string()).optional(),
    status: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace SlaTrackersListRequest {
    interface Raw {
        created_date?: DateTimeFilter.Raw | null;
        cursor?: string | null;
        limit?: number | null;
        mode?: ListMode.Raw | null;
        modified_date?: DateTimeFilter.Raw | null;
        sort_by?: string[] | null;
        stage?: string[] | null;
        status?: string[] | null;
    }
}
